# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c8d0eea81ef9cd87d86f26ddbb94bbba08f375dbec4e50073bc44a10a0d85fc6922fdbc6bdf63da587956f17877456af144690b2abe3d32b384e760a75be847

test:
  secret_key_base: 324f30839004052e7f2f5def2b41a0c46ed591c8054af251c2abd677cf7d5a8c5b06b6fd21325c66bc28f8b78500533a62f8319b4b04abab6d6622510ec55bbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
